# run via: docker-compose -f Air_quality.yaml up -d
version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - mosquitto-storage:/mosquitto
    restart: always
  
  influxdb:
    image: influxdb:1.8.10
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=air_quality
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=air_quality
      - INFLUXDB_USER_PASSWORD=air_quality
    restart: on-failure:10
    ports:
      - 8086:8086
    restart: always
  
  grafana:
    image: grafana/grafana:10.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    restart: always

volumes:
  mosquitto-storage:
  grafana-storage:
  influxdb-storage:

# to access the data on the host, use the following commands:
# docker volume ls
# docker volume inspect (the name of the volume)